version: '3.8'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.15
    container_name: chromadb-server
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/data
      - ./config:/app/config:ro
    environment:
      - CHROMA_PERSIST_DIRECTORY=/data
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chromadb_data:
    driver: local
